### ISSUE TITLE
[Feature Request] Javascript: Italicize more words

### ISSUE THREAD

**Issue by Vorror** [samrap/outrun-theme-vscode#2]
### Feature Request:

Currently, certain javascript keywords aren't italicized (this, super, extends). Could outrun be updated to support them?

<img width="567" alt="screen shot 2018-06-30 at 11 44 45 am" src="https://user-images.githubusercontent.com/3613230/42126782-2dd22712-7c5b-11e8-8399-a3f951b16967.png">

For example, the "RED" theme does this correctly(except extends)

<img width="523" alt="screen shot 2018-06-30 at 11 50 39 am" src="https://user-images.githubusercontent.com/3613230/42126837-e9024a9e-7c5b-11e8-8697-bdbb7629db24.png">

p.s Found your theme on reddit. Great job :)

**Comment by samrap** [comment]
Glad you're trying it out :)

I can definitely do this. I will look into a couple themes that have better JS configs and get some more italics where appropriate.

**Comment by Vorror** [comment]
@samrap Thanks!

Currently I'm using, which works for me

```
 "editor.tokenColorCustomizations": {
        "[Outrun]": {
            "textMateRules": [
                {
                    "scope": [
                        "variable.language.this.js",
                        "variable.language.super.js"
                    ],
                    "settings": {
                        "foreground": "#F4B80C",
                        "fontStyle": "italic"
                    }
                }
            ]
        }
    }
```

**Comment by samrap** [comment]
Thanks for sharing that. I'll take a look at it tomorrow and get it published early this week :)

**Comment by samrap** [comment]
@Vorror Update has been made and tagged at 0.0.2. I went with cyan for the keyword foreground. I have a lot of cleaning up to do for JavaScript and some of the global syntax colors as I start to use this more and the cyan will look best after the next version update.

**Comment by Vorror** [comment]
@samrap You're awesome :) I removed my setting. I think cyan looks a lot better.

I had a full work day with your theme and it's awesome. The only other thing I changed was the tabs:
<img width="436" alt="screen shot 2018-07-02 at 7 37 02 pm" src="https://user-images.githubusercontent.com/3613230/42191196-a129700a-7e2f-11e8-935d-9a9ded8036d8.png">

I noticed it took me 1-2 seconds longer than normal to find the active tab so I made the above change. It's definitely a very personal preference. Now I'm always aware of the current tabs position when it's in my periphery. And I think it looks a bit better than the gray bar between the tabs.

**Comment by samrap** [comment]
I'm digging those tabs. I'll be sure to add that in on the next version.

As I said, this hasn't been used much by me in the wild (this is actually my first week _using_ it too), so needless to say there's a lot of fine-tuning to do. I'm also brand-new to VS Code itself, so there's probably a lot features I haven't tested the theme in yet.

Super stoked to hear you're liking it, you can expect some subtle clean-up over the next few weeks.
