### ISSUE TITLE
Highlight more in JS

### ISSUE THREAD

**Issue by WandersonAlves** [samrap/outrun-theme-vscode#3]
Hi, first of all I would like to say that I loved your theme!
The colors are awesome!

If possible, can you make function names declarations `this` keyword, decorators declarations and objects attributes of js, vue, ts, tsx, jsx files to be highlighted?

Currently in a vue file, your theme behave like below

![screenshot from 2018-07-05 14-11-51](https://user-images.githubusercontent.com/9141449/42337531-7848a3ba-805d-11e8-837a-b8729347e424.png)

In ts files, your theme behave like below

![screenshot from 2018-07-05 14-15-05](https://user-images.githubusercontent.com/9141449/42337670-d749e590-805d-11e8-9c6f-cb15d370b214.png)

And the screenshot below is from `cobalt2` theme that have everything highlighted

![screenshot from 2018-07-05 14-16-16](https://user-images.githubusercontent.com/9141449/42337741-085c0848-805e-11e8-9103-d343225321c5.png)

Thanks dude!

**Comment by WandersonAlves** [comment]
Oh, and i saw on #2 that someone posted his configs about italic words, so here is mine:

```
"editor.tokenColorCustomizations": {
        "textMateRules": [
            {
                "scope": [
                    "comment",
                    "keyword",
                    "constant",
                    "storage.modifier",
                    "storage.type.class.js",
                ],
                "settings": {
                    "fontStyle": "italic",
                }
            },
            {
                "scope": [
                    "invalid",
                    "keyword.operator",
                    "constant.numeric.css",
                    "keyword.other.unit.px.css",
                    "constant.numeric.decimal.js",
                    "constant.numeric.json"
                ],
                "settings": {
                    "fontStyle": ""
                }
            }
        ]
    },
```

**Comment by samrap** [comment]
As I mentioned in #2 , I will be going through the color scheme for various languages (including JS) with a fine-toothed comb over the next few weeks. While I do plan on improving the highlighting of various keywords, I do not plan on making this theme as colorful as something like cobalt. My goal with this theme is to be more minimal, using only the bright synthwave color palette on the more important scopes. Stay tuned over the next few weeks as I push updates, but I am going to close this issue for now and open a new one that references this. Thanks for trying out the theme!
