### ISSUE TITLE
[Feature Request] Lower scrollbar opacity

### ISSUE THREAD

**Issue by Vorror** [samrap/outrun-theme-vscode#5]
Just another thing I noticed. Currently, the scrollbar is fully opaque, which prevents the user from seeing indicators in the scrollbar:
<img width="61" alt="screen shot 2018-07-08 at 11 53 29 pm" src="https://user-images.githubusercontent.com/3613230/42429944-266be7b4-830a-11e8-98b7-aa0f1452679a.png">

My current setting:
<img width="102" alt="screen shot 2018-07-08 at 11 51 22 pm" src="https://user-images.githubusercontent.com/3613230/42429894-db43b2d0-8309-11e8-9400-830f086b002e.png">

<img width="393" alt="screen shot 2018-07-08 at 11 49 41 pm" src="https://user-images.githubusercontent.com/3613230/42429908-f0a42b50-8309-11e8-81cf-561a5b0897ce.png">

**Comment by samrap** [comment]
Really appreciate the detailed reports. I'll be sure to get this added in shortly.

**Comment by samrap** [comment]
Updated in 0.2.0!
