### ISSUE TITLE
Unable to see underscore character ( _ ) inside terminal

### ISSUE THREAD

**Issue by elluvium** [samrap/outrun-theme-vscode#6]
Please, find below some screenshots of the same file in VS Code console and standard Ubuntu: 

![image](https://user-images.githubusercontent.com/3740825/43836437-0ab9b98e-9b1e-11e8-9eee-bda92a606316.png)

![image](https://user-images.githubusercontent.com/3740825/43836583-7858c8e0-9b1e-11e8-8025-ada18d5f8fd2.png)

**Comment by samrap** [comment]
Interesting, will take a look at this. Planning some more updates based on feedback soon as well

**Comment by samrap** [comment]
I believe this might be an issue with your font or configured line height, as I cannot replicate this issue on  my machine:

<img width="591" alt="screen shot 2018-08-26 at 12 40 03 pm" src="https://user-images.githubusercontent.com/5227553/44632318-415c7180-a92d-11e8-8f48-a86e467e9ce0.png">

**Comment by elluvium** [comment]
That's weird but after VS Code last update everything became fine. Seems it's better to close this issue. Thank you!
